;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================
;0C171F
[colors]
background = #07293C
background-alt = #02405f
foreground = #FFFFFF
primary = #00BBFF
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/bar1]
width = 100%
height = 20pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 11pt
border-color = #00000000

padding-left = 0

;separator = |
separator-foreground = ${colors.disabled}

font-0 = Fira-Sans:size=10;2

modules-left = xworkspaces xwindow
modules-right = filesystem pulseaudio xkeyboard memory cpu wlan eth date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
;label-active-background = ${colors.background-alt}
label-active-background = #009493
;label-active-underline= #FFFFFF
label-active-padding = 4

label-occupied = %name%
label-occupied-padding = 4
label-occupied-background = #006982

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 4

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 4


[module/xwindow]
label-foreground = #FFFFFF
format-background = #02405f
format-padding = 4
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#FFFFFF}storage used(%mountpoint%): %percentage_used%%
label-mounted-background = #023F5E
label-mounted-padding = 4

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}
label-unmounted-background = #023F5E
label-unmounted-padding = 4

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "volume "
;format-volume-prefix-foreground = ${colors.primary}
format-volume-prefix-foreground = #FFFFFF
format-volume = <label-volume>
format-volume-background = #005473
format-volume-padding = 4

label-volume = %percentage%%

label-muted = muted
;label-muted-foreground = ${colors.disabled}
format-prefix-foreground = #FFFFFF
label-muted-background = #005473
label-muted-padding = 4


;[module/xkeyboard]
;type = internal/xkeyboard
;blacklist-0 = num lock
;
;label-layout = %layout%
;label-layout-foreground = ${colors.primary}
;
;label-indicator-padding = 2
;label-indicator-margin = 1
;label-indicator-foreground = ${colors.background}
;label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "ram "
;format-prefix-foreground = ${colors.primary}
format-prefix-foreground = #FFFFFF
label = %percentage_used:2%%
format-padding = 4
format-background = #006982

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "cpu "
;format-prefix-foreground = ${colors.primary}
format-prefix-foreground = #FFFFFF
label = %percentage:2%%
format-background = #007e8c
format-padding = 4

;[network-base]
;type = internal/network
;interval = 5
;format-connected = <label-connected>
;format-disconnected = <label-disconnected>
;label-disconnected = %{F#00BBFF}%ifname%%{F#707880} disconnected

;[module/wlan]
;inherit = network-base
;interface-type = wireless
;label-connected = %{F#00BBFF}%ifname%%{F-} %essid% %local_ip%
;format-background = #005473

;[module/eth]
;inherit = network-base
;interface-type = wired
;label-connected = %{F#00BBFF}%ifname%%{F-} %local_ip%
;format-background = #005473
;format-padding = 2

[module/date]
type = internal/date
interval = 1
format-background = #009493
format-padding = 4

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
;label-foreground = ${colors.primary}
label-foreground = #FFFFFF

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
